version: '2'

services:
    mysql:
        image: mysql:5.7
        ports:
            - 1423:3306
        volumes:
            - /var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: docker

    nginx:
        image: nginx:1.10.2
        ports:
            - 7200:80
        restart: always
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./public:/var/www/html
        links:
            - php
        depends_on:
            - php

    php:
        build: docker/php
        expose:
            - 9000
        restart: always
        volumes:
            - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./public:/var/www/html
        links:
            - mysql
